name: CI
on:
  push:
    branches:
      - main
      - master
      - dev
      - release-*
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main
      - master
      - dev
      - release-*

jobs:
  CI:
    strategy:
      matrix:
        # node-version: [10.x, 12.x, 14.x]
        node-version: [14.x]
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: testtest
          POSTGRES_PASSWORD: example
          POSTGRES_DB: theinvitate
        ports:
          - 5433:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Set up nodejs version ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install package
      run: npm install
    - name: Linter
      run:  npm run lint
    - name: Format
      run:  npm run pretty
    - name: Build
      run: npm run build --if-present
    - name: Test
      run: |
        npx prisma db push
        npm run test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
